#dev
deployment:
  strategy: rsync
  user: root
  from: ./.mage/artifact/
  to: /var/www/deploy
  document-root: '/var/www/html'
releases:
  enabled: true
  max: 5
  symlink: current
  directory: releases
hosts:
  - "your-url.com"
  pre-deploy:
    - typo3-artifact:
        excludes:
          - /bin
          - /deployment
          - /fileadmin
          - /typo3
          - /typo3temp
          - /uploads
          - composer.lock
          - /composer.json
          - /index.php
          - typo3conf/LocalConfiguration.php
          - atlassian-ide-plugin.xml
          - .editorconfig
          - .git*
          - .idea
          - .mage
          - .vagrant
          - bower_components
          - node_modules
          - Vagrantfile
  on-deploy:
  post-release:
    - clear-op-cache: {frontend-url: 'https://your-url.com'}
  post-deploy: