#dev
deployment:
  strategy: rsync
  user: www
  from: ./.mage/artifact/
  to: /var/www/deploy
  document-root: '/var/www/html'
releases:
  enabled: true
  max: 5
  symlink: current
  directory: releases
hosts:
  - "your-url.com"
tasks:
  pre-deploy:
    - typo3-artifact
  on-deploy:
  post-release:
    - typo3-release
    - clear-op-cache: {frontend-url: 'http://your-url.com'}
    - typo3-console: {command: cache:flush}
  post-deploy:
